[project]
name = "birkhoff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "networkx>=2.0",
    "numpy>=2.3.3",
]

[dependency-groups]
dev = []
